config/routes.rb
Rails.application.routes.draw do




  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources 'skills'
  resources 'experiences'
  resources 'educations'
  resources 'services'
  resources 'testimonials'

  get 'welcome/index'
  get 'welcome/about'

  root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :profile_picture, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
   validates_attachment_content_type :profile_picture, content_type: /\Aimage\/.*\z/

   has_many :skills
   has_many :experiences
   has_many :educations
   has_many :services
   has_many :testimonials


  def full_name
    return "#{first_name} #{last_name}"
  end

end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  def show
    @user = current_user
    @exp = @user.experiences.sort_by &:to
    @edu = @user.educations.sort_by &:to
    @ser = @user.services
    @tes = @user.testimonials
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :description, :mission, :profile_picture])
  end

end

app/views/users/_educationdisplay.html.erb
<!--Main title-->

<div class="main-title">
  <h1>
    education
    <% if @user.id == current_user.id %>
    <%= link_to "edit", user_educations_path(@user), class: "btn btn-link btn-sm" %>
    <% end %>
  </h1>

  <!-- <div class="divider">
  <div class="zigzag large clearfix "  data-svg-drawing="yes" >
  <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
  <path d="M1.357,12.26 10.807,2.81 20.328,12.332
  29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
</svg>
</div>
</div> -->
</div>
<!--End main title-->


<!--Content-->
<div class="content">

  <!--Block content-->
  <div class="block-content">


    <!--Timeline-->
    <div class="timeline education">


      <!--Row-->
      <div class="row ">


        <div class="col-md-12">


          <!--Experience holder-->
          <div class="exp-holder margTop">

            <% @edu.each do |edu| %>

            <!--Experience-->
            <div class="exp">
              <div class="hgroup" >
                <h4><%= edu.degree%> – <%=edu.institute%> </h4>
                <h6><i class="icon-calendar"></i><%=edu.from%> - <%=edu.to%></h6>
              </div>
              <p>
                <%=edu.description%>
              </p>
            </div>
            <!--End experience-->
            <%end%>

          </div>
          <!--End experience holder-->
        </div>


      </div>
      <!--End row-->

    </div>
    <!--End timeline-->

  </div>
  <!--End block content-->


</div>
<!--End content-->

<!--Experience-->
<!-- <div class="exp">
<div class="hgroup" >
<h4>School Of Science – Mutation Media </h4>
<h6><i class="icon-calendar"></i>May 2015 - Sept 2015</h6>
</div>
<p>Ut enim ad minim veniam, quis nostrud exerc. Irure dolor in reprehend
incididunt labore
et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
ex ea commodo consequat inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>														</div> -->
<!--End experience-->

app/views/users/_experiencedisplay.html.erb
<!--Main title-->
<div class="main-title">
  <h1>
    experience
    <% if @user.id == current_user.id %>
      <%= link_to "edit", user_experiences_path(@user), class: "btn btn-link btn-sm" %>
    <% end %>
  </h1>
  <!-- <div class="divider">
    <div class="zigzag large clearfix "  data-svg-drawing="yes" >
      <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
        <path d="M1.357,12.26 10.807,2.81 20.328,12.332 29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
      </svg>
    </div>
  </div> -->
</div>
<!--End main title-->

<!--Content-->
<div class="content">

  <!--Block content-->
  <div class="block-content ">

    <!--Timeline-->
    <div class="timeline experience">

      <!--Row-->
      <div class="row ">

        <div class="col-md-12">

          <!--Experience holder-->
          <div class="exp-holder margTop">

            <% @exp.each do |exp| %>
            <!--Experience-->
            <div class="exp">
              <div class="hgroup" >
                <h4><%= exp.position %> – <%= exp.company_name%> </h4>
                <!-- <h6><i class="icon-calendar"></i>Feb 2015 - <span class="current">Current</span></h6> -->
                <h6><i class="icon-calendar"></i><%= exp.from%> - <%= exp.to%></h6>
              </div>
              <p>
                <%= exp.description%>
              </p>
            </div>
            <!--End experience-->
            <% end %>
              <!--Experience-->
              <!-- <div class="exp">
                <div class="hgroup" >
                  <h4>Web Developer – Mutation Media </h4>
                  <h6><i class="icon-calendar"></i>Sept 2015 - Nov 2015</h6>
                </div>
                <p>Ut enim ad minim veniam, quis nostrud exerc. Irure dolor in reprehend
                  incididunt labore
                  et dolore magna aliqua. Ut enim ad minim
                  veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                  ex ea commodo consequat inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                </div> -->
                <!--End experience-->

                <!-- Experience-->
                <!-- <div class="exp">
                  <div class="hgroup" >
                    <h4>SDK Developer – Mutation Media </h4>
                    <h6><i class="icon-calendar"></i>May 2015 - Sept 2015</h6>
                  </div>
                  <p>Ut enim ad minim veniam, quis nostrud exerc. Irure dolor in reprehend
                    incididunt labore
                    et dolore magna aliqua. Ut enim ad minim
                    veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                  </div> -->
                  <!--End experience -->

                </div>
                <!--End experience holder-->
              </div>

            </div>
            <!--End row-->

          </div>
          <!--End timeline-->

        </div>
        <!--End block content-->

      </div>
      <!--End content-->

app/views/users/_header.html.erb
<header id="header">

  <!--Main header-->
  <div class="main-header">

    <!--Profile image-->
    <figure class="img-profile">
      <!-- <img src="img/profile.jpg" alt=""/> -->
      <%= image_tag(@user.profile_picture.url, alt: "Edit Entry", :class => "card-img-top" ) %>

      <figcaption class="name-profile">
        <span><%= @user.full_name %><sup>&reg;</sup></span>
      </figcaption>

    </figure>
    <!--End profile image-->

    <!--Main navigation-->
    <nav id="main-nav" class="main-nav clearfix tabbed">

      <ul>
        <li ><a href="#about"><i class="icon-user"></i>About</a></li>
        <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
        <li><a  href="#portfolio"><i class="icon-camera"></i>Portfolio</a></li>
        <li><a  href="#blog"><i class="icon-chat"></i>Blog</a></li>
        <li><a  href="#contact"><i class="icon-phone"></i>Contact</a></li>
      </ul>

    </nav>
    <!--End main navigation-->

  </div>
  <!--End main header-->

  <div class="bottom-header bgWhite ofsTSmall ofsBSmall tCenter">
    <ul class="social">
      <li><a href="#"><i class="icon-facebook"></i></a></li>
      <li><a href="#"><i class="icon-twitter"></i></a></li>
      <li><a href="#"><i class="icon-linkedin"></i></a></li>
    </ul>

    <p>&copy; 2015 Mutationthemes.</p>

  </div>




</header>

<!--
<div class="card" style="width: 30rem;">
<%= image_tag(@user.profile_picture.url, size: "299x250", alt: "Edit Entry", :class => "card-img-top" ) %>

<ul id="wrapper">
<li><%= link_to "logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-in" %></li>
<li><a href="#">Projects <span class="number">3</span> </a></li>
<li><a href="#">Music <span class="number">4</span> </a></li>
<li><a href="#">Photos <span class="number">2</span> </a></li>
</ul>

<div class="btn-group link-button ">
<button type="button" class="btn btn-sm btn-link">
<%= link_to "http://www.facebook.com/" do %>
<%=   image_tag("socialnetworkslogos/cir/png/facebook.png", size: "30x30", alt: "Edit Entry") %>
<% end %>
</button>
<button type="button" class="btn btn-sm btn-link">
<%= link_to "http://www.twitter.com/" do %>
<%=   image_tag("socialnetworkslogos/cir/png/twitter.png", size: "30x30", alt: "Edit Entry") %>
<% end %>
</button>
<button type="button" class="btn btn-sm btn-link">
<%= link_to "http://www.linkedin.com/" do %>
<%=   image_tag("socialnetworkslogos/cir/png/linkedin.png", size: "30x30", alt: "Edit Entry") %>
<% end %>
</button>
</div>

<div class="copywrite">
<p>by @-|)</p>
</div>

</div> -->

app/views/users/_servicesdisplay.html.erb
<!--Main title-->

<div class="main-title">
  <h1>
    service
    <% if @user.id == current_user.id %>
      <%= link_to "edit", user_services_path(@user), class: "btn btn-link btn-sm" %>
    <% end %>
  </h1>
  <!-- <div class="divider">
    <div class="zigzag large clearfix "  data-svg-drawing="yes" >
      <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
        <path d="M1.357,12.26 10.807,2.81 20.328,12.332
        29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
      </svg>
    </div>
  </div> -->
</div>
<!--End main title-->

<!--Content-->
<div class="content">

  <!--Block content-->
  <div class="block-content ">

    <!--Services-->
    <div class="services">

      <!--Row-->
      <div class="row ">

        <!--Block-->
        <div class="block service tCenter">

          <table class="table">
            <thead></thead>
            <tbody>
              <% @ser.each do |ser| %>
              <tr>
                <div class="col-md-4">
                  <!-- <div class="ico">
                    <i class="icon-lifebuoy"></i>
                  </div> -->

                  <div class="det">
                    <h3><%=ser.name%></h3>
                    <p>
                      <%=ser.description%>.
                    </p>
                  </div>
                </div>

              </tr>
              <%end%>
            </tbody>
          </table>




        </div>
        <!--End block-->
      </div>
      <!--End row-->





  </div>
  <!--End servcices-->

</div>
<!--End block content-->

</div>
<!--End content-->

<!-- <div class="row "> -->

  <!--Block-->
  <!-- <div class="block service tCenter">

    <div class="col-md-4">
      <div class="ico">
        <i class="icon-monitor"></i>
      </div>

      <div class="det">
        <h3>Web Design</h3>
        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.</p>
      </div>
    </div>

    <div class="col-md-4">
      <div class="ico">
        <i class="icon-tools"></i>
      </div>

      <div class="det">
        <h3>development</h3>
        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.</p>
      </div>

    </div>

    <div class="col-md-4">
      <div class="ico">
        <i class="icon-lamp"></i>
      </div>
      <div class="det">
        <h3>Branding</h3>
        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.</p>
      </div>

    </div>

  </div> -->
  <!--End block-->
<!-- </div> -->
<!--End row-->

<!--Row-->
<!-- <div class="row"> -->

  <!--Divider-->
  <!-- <div class="divider-m tCenter margTSmall margBSmall clearfix">

    <div class="col-md-12">
      <div class="zigzag medium clearfix "  data-svg-drawing="yes" >
        <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="45" height="5" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
          <path d="M1.357,12.26 10.807,2.81 20.328,12.332 29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
        </svg>
      </div>
    </div>

  </div> -->
  <!--End divider-->

<!-- </div> -->
<!--End row-->


<!--Row-->

app/views/users/_skilldisplay.html.erb
<!--Main title-->
<div class="main-title">
  <h1>professional skills
    <% if @user.id == current_user.id %>
    <%= link_to "edit skills", user_skills_path(@user), class: "btn btn-link btn-sm" %>
    <% end %>
  </h1>
  <!-- <div class="divider">
  <div class="zigzag large clearfix "  data-svg-drawing="yes" >
  <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
  <path d="M1.357,12.26 10.807,2.81 20.328,12.332
  29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
  </svg>
  </div>
  </div> -->
</div>
<!--End main title-->

<!--Content-->
<div class="content">

  <!--Block content-->
  <!-- coding skills rows -->
  <div class="block-content  margBMedium">
    <!--Skill design-->
    <div class=" skill prs">
      <!--Row-->
      <div class="row ">

        <div class="vc">

          <div class="col-md-11">

            <ul class="skills-list clearfix">
              <li>
                <% @user.skills.each do |skill| %>
                <% if skill.catagory == 'coding' %>
                <h4><%= skill.name %></h4>
                <div class="progress">
                  <div class="percentage">
                    <%= skill.level %>%
                  </div>
                </div>
                <% end %>
                <% end %>
              </li>
            </ul>
          </div>
          <!-- left title -->
          <div class="col-md-1">
            <div class="title prs">
              <span>coding</span>
            </div>
          </div>

        </div>
      </div>
      <!--End row-->

    </div>
    <!--End skill design-->

  </div>
  <!--End block content-->

  <!--Block content-->
  <div class="block-content margBMedium">

    <!--Skill design-->
    <div class=" skill dev">

      <!--Row-->
      <div class="row">
        <div class="vc">

          <div class="col-md-11">

            <ul class="skills-list clearfix">
              <li>
                <% @user.skills.each do |skill| %>
                <% if skill.catagory == 'design' %>
                <h4><%= skill.name %></h4>
                <div class="progress">
                  <div class="percentage">
                    <%= skill.level %>%
                  </div>
                </div>
                <% end %>
                <% end %>
              </li>
            </ul>
          </div>

          <div class="col-md-1">
            <div class="title prs">
              <span>design's</span>
            </div>
          </div>

        </div>
      </div>
      <!--End row-->

    </div>
    <!--End skill design-->

  </div>
  <!--End block content-->


  <!--Block content-->
  <div class="block-content">

    <!--Skill design-->
    <div class=" skill des">

      <!--Row-->
      <div class="row ">

        <div class="vc">

          <div class="col-md-11">

            <ul class="skills-list clearfix">
              <li>
                <% @user.skills.each do |skill| %>
                <% if skill.catagory == 'soft_skills' %>
                <h4><%= skill.name %></h4>
                <div class="progress">
                  <div class="percentage">
                    <%= skill.level %>%
                  </div>
                </div>
                <% end %>
                <% end %>
              </li>
            </ul>

          </div>

          <div class="col-md-1">
            <div class="title prs">
              <span>soft skill's</span>
            </div>
          </div>

        </div>
      </div>
      <!--End row-->

    </div>
    <!--End skill design-->

  </div>
  <!--End block content-->

</div>
<!--End content-->

app/views/users/_testemonialsdesplay.html.erb
<!--Main title-->

<div class="main-title">
  <h1>
    testimonials
    <% if @user.id == current_user.id %>
      <%= link_to "edit", user_testimonials_path(@user), class: "btn btn-link btn-sm" %>
    <% end %>
  </h1>
  <!-- <div class="divider">
    <div class="zigzag large clearfix "  data-svg-drawing="yes" >
      <svg xml:space="preserve" viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
        <path d="M1.357,12.26 10.807,2.81 20.328,12.332
        29.781,2.879 39.223,12.321 48.754,2.79 58.286,12.321 67.815,2.793 "  style="stroke-dasharray: 93.9851, 93.9851; stroke-dashoffset: 0;"/>
      </svg>
    </div>
  </div> -->
</div>

<!--End main title-->

<!--Content-->
<div class="content">

  <!--Block content-->
  <div class="block-content ">


    <!--Testimonilas-->
    <div class="testimonials">


      <!--Row-->
      <div class="row ">

        <div class="col-md-12">

          <!--Slider-->
          <div class="testi clearfix ">


            <ul id="testimonial-carousel">

              <% @tes.each do |tes| %>
              <li>



                <div class="block-quote">
                  <div class="block-img">
                    <% if tes.pic.exists? %>
                      <%= image_tag tes.pic.url %>
                    <% else%>
                      <img src="/assets/default.jpg" alt="default image">
                    <% end %>
                  </div>

                  <div class="block-icon">
                    <img src="/assets/icon_quote.png" alt="default image">
                  </div>

                  <h3 class="block-profile">
                    <%= tes.persons_name %>
                    <span> <%= tes.persons_designantion%> / <%= tes.company%> </span>
                  </h3>
                  <blockquote>
                    <%= tes.description%>
                  </blockquote>

                  </div>
                </li>
                <%end%>
                <!-- <li>
                  <div class="block-quote">
                    <div class="block-img"><img alt="" src="img/testimonial/2.jpg"></div>
                    <div class="block-icon"><i class="icon-quote"></i></div>
                    <h3 class="block-profile">Carlose Smith<span> CEO / Split Inc</span></h3>
                    <blockquote>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
                      totam rem aperiam, eaque ipsa quae ab illo
                      inventore veritatis et quasi architecto beatae vitae dicta.</blockquote>

                    </div>
                  </li> -->


                </ul>

              </div>
              <!--End  slider-->


            </div>


          </div>
          <!--End row-->


        </div>
        <!--End testimonials-->

      </div>
      <!--End block content-->


    </div>
    <!--End content-->