config/routes.rb
Rails.application.routes.draw do




  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources 'skills'
  resources 'experiences'
  resources 'educations'
  resources 'services'
  resources 'testimonials'

  get 'welcome/index'
  get 'welcome/about'

  root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController

  def index
    @user = current_user
    @educations = @user.educations
  end


  def new
    @education = Education.new
    @user = current_user
  end

  def create
    @education = Education.create(education_params)
    @user = current_user.id
    @education.user_id = @user

    respond_to do |format|
      if @education.save
        format.html { redirect_to education_path(@education), notice: 'record successfully added.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @education = Education.find(params[:id])
    @user = @education.user_id
  end


  def edit
    @education = Education.find(params[:id])
    @user = @education.user_id
  end

  def update

    @education = Education.find(params[:id])
    @user = @education.user_id

    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to education_path(@education), notice: 'record successfully updated.' }
        # format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        # format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @education = Education.find(params[:id])
    @user = @education.user_id

    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_path, notice: 'record was successfully deleted.' }
      # format.json { head :no_content }
    end
  end
  #
  #
  private

  def education_params
    params.require(:education).permit(:institute, :degree, :description, :from, :to, :user_id)
  end

end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<form_tag class="form-horizontal" >

  <%= form_for([@education]) do |f| %>

  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% @education.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Institute Name:</label>
    <div class="col-sm-10">
      <%= f.text_field :institute, class: 'form-control', placeholder: "name of the institute from which you complete your degree" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Degree:</label>
    <div class="col-sm-10">
      <%= f.text_field :degree, class: 'form-control', placeholder: "eg MBS BSCS BSEE etc" %>
    </div>
  </div>


  <div class="form-group">
    <label class="control-label col-sm-2" for="email">From:</label>
    <div class="col-sm-10">
      <%= f.date_field :from, placeholder: "dd/mm/yyyy", class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="email">To:</label>
    <div class="col-sm-10">
      <%= f.date_field :to, placeholder: "dd/mm/yyyy", class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Description:</label>
    <div class="col-sm-10">
      <%= f.text_area :description, placeholder: "description", class: 'form-control', rows: 10 %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default pull-right">Submit</button>
    </div>
  </div>
</form>
  <% end %>

app/views/educations/edit.html.erb
<%= render 'form', :@user => @user, :@education => @education %>
<%= link_to 'cancel', education_path %>

app/views/educations/index.html.erb
<table class="table table-inverse table-education">
  <thead>
    <tr>
      <th>Institute</th>
      <th>Degree</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @educations.each do |edu| %>

    <tr>
      <td><%=edu.institute%></td>
      <td><%=edu.degree%></td>
      <td>

        <%= link_to 'show', education_path(edu.id), class: 'btn btn-link' %>
        <%= link_to 'Delete', [edu], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link'  %>

      </td>
    </tr>
    <%end%>
  </tbody>
</table>


<%= link_to 'Add another education record', new_education_path(@user), class: 'btn btn-link' %>
<!-- <%#= link_to 'back', user_path(@user), class: 'btn btn-link' %> -->

app/views/educations/new.html.erb
<%= render 'form', :@user => @user %>
<%= link_to 'cancel', educations_path %>

app/views/educations/show.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <!-- <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1> -->
  <h3>degree details</h3>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:institute) %>:</strong></dt>
  <dd><%= @education.institute %></dd>
  <dt><strong><%= model_class.human_attribute_name(:degree) %>:</strong></dt>
  <dd><%= @education.degree %></dd>
  <dt><strong><%= model_class.human_attribute_name(:starting_date) %>:</strong></dt>
  <dd><%= @education.from %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ending_date) %>:</strong></dt>
  <dd><%= @education.to %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @education.description %></dd>
</dl>

<%= link_to 'back',  educations_path, :class => 'btn btn-link' %>
<% if (current_user.id == @user) %>
  <%= link_to 'Edit',  edit_education_path(@education), :class => 'btn btn-link'  %>
  <%= link_to 'Destroy', [@education], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-link'  %>
<% end %>