config/routes.rb
Rails.application.routes.draw do




  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources 'skills'
  resources 'experiences'
  resources 'educations'
  resources 'services'
  resources 'testimonials'

  get 'welcome/index'
  get 'welcome/about'

  root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord

  has_attached_file :pic, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :pic, content_type: /\Aimage\/.*\z/

  belongs_to :user
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController

  def index
    @user = current_user
    @tes = @user.testimonials
  end

  def new
    @tes = Testimonial.new
    @user = current_user
  end

  def create
    @tes = Testimonial.create(testimonial_params)
    @user = current_user.id
    @tes.user_id = @user

    respond_to do |format|
      if @tes.save
        format.html { redirect_to testimonial_path(@tes), notice: 'skill was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @tes = Testimonial.find(params[:id])
    @user = @tes.user_id
  end

  def edit
    @tes = Testimonial.find(params[:id])
    @user = @tes.user_id
  end

  def update

    @tes = Testimonial.find(params[:id])
    @user = @tes.user_id

    respond_to do |format|
      if @tes.update(testimonial_params)
        format.html { redirect_to testimonial_path(@tes), notice: 'record was successfully created.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tes = Testimonial.find(params[:id])
    @user = @tes.user_id

    @tes.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_path, notice: 'record was successfully created.' }
    end
  end


  private

  def testimonial_params
    params.require(:testimonial).permit(:persons_name, :persons_designantion, :description, :company, :pic, :user_id)
  end

end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<form_tag class="form-horizontal", html: { multipart: true } >

  <%= form_for([@tes]) do |f| %>

  <% if @tes.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tes.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% @tes.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Person Name:</label>
    <div class="col-sm-10">
      <%= f.text_field :persons_name, class: 'form-control', placeholder: "name" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Company:</label>
    <div class="col-sm-10">
      <%= f.text_field :company, class: 'form-control', placeholder: "company name" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Person Designation:</label>
    <div class="col-sm-10">
      <%= f.text_field :persons_designantion, class: 'form-control', placeholder: "software engineer, accountant, ceo etc" %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Description:</label>
    <div class="col-sm-10">
      <%= f.text_area :description, placeholder: "testimonial", class: 'form-control', rows: 10 %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Image:</label>
    <div class="col-sm-10">
      <%= f.file_field :pic %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default pull-right">Submit</button>
    </div>
  </div>

  <% end %>

</form>

app/views/testimonials/edit.html.erb
<%= render 'form', :@user => @user %>
<%= link_to 'cancel', testimonial_path %>

app/views/testimonials/index.html.erb
<table class="table table-inverse table-education">
  <thead>
    <tr>
      <th>persons name</th>
      <th>persons company</th>
      <th>persons designantion</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tes.each do |tes| %>

    <tr>
      <td><%=tes.persons_name%></td>
      <td><%= tes.company  %></td>
      <td><%=tes.persons_designantion%></td>
      <td>
        <%= link_to 'show', testimonial_path(tes.id), class: 'btn btn-link' %>
        <%= link_to 'Delete', [tes], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link'  %>
      </td>
    </tr>
    <%end%>
  </tbody>
</table>


<%= link_to 'Add another testimonial record', new_testimonial_path, class: 'btn btn-link pull-right' %>
<%#= link_to 'back', user_path(@user), class: 'btn btn-link pull-right' %>

app/views/testimonials/new.html.erb
<%= render 'form', :@user => @user %>
<%= link_to 'cancel', testimonials_path(@user) %>

app/views/testimonials/show.html.erb
<%- model_class = Testimonial -%>
<div class="page-header">
  <!-- <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1> -->
  <h3>details</h3>
</div>

<div class="row">

  <div class="col-md-6">
    <% if @tes.pic.exists? %>
      <!-- <%= image_tag(@user.profile_picture.url, alt: "Edit Entry", :class => "card-img-top" ) %> -->
      <%= image_tag @tes.pic.url %>
    <% else%>
      <img src="/assets/default.jpg" alt="default image">
      <span class="pull-right">no picture provided</span>
    <% end %>
  </div>

  <div class="col-md-6">
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:from) %>:</strong></dt>
      <dd><%= @tes.persons_name %></dd>
      <dt><strong><%= model_class.human_attribute_name(:company) %>:</strong></dt>
      <dd><%= @tes.company %></dd>
      <dt><strong><%= model_class.human_attribute_name(:designation) %>:</strong></dt>
      <dd><%= @tes.persons_designantion %></dd>
      <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
      <dd><%= @tes.description %></dd>
    </dl>


  </div>

</div>

<%= link_to 'back',  testimonials_path, :class => 'btn btn-link pull-right' %>
<% if (current_user.id == @user ) %>
  <%= link_to 'Edit',  edit_testimonial_path(@tes), :class => 'btn btn-link pull-right'  %>
  <%= link_to 'Destroy', [@tes], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-link pull-right'  %>
<% end %>